/**
 * implementation-tasks.ts — recovery synthesis for missing implementation-tasks.md.
 */

import { writePlanArtifact } from "pi-zflow-artifacts"
import { resolvePlanArtifactPath } from "pi-zflow-artifacts/artifact-paths"

import { parseExecutionGroupsMd } from "../execution-groups.js"

/**
 * Ensure `implementation-tasks.md` exists for a plan version.
 *
 * When the planner fails to produce the artifact but `execution-groups.md`
 * exists and parses, this synthesizes a recovery artifact that is useful for
 * inspection and repair but explicitly not approvable as a final plan.
 *
 * @param changeId - The change identifier.
 * @param planVersion - The plan version (for example `v1`).
 * @param cwd - Working directory (optional).
 * @returns `true` when a synthesized artifact was created.
 */
export async function ensureImplementationTasksArtifact(
  changeId: string,
  planVersion: string,
  cwd?: string,
): Promise<boolean> {
  const { default: fs } = await import("node:fs/promises")
  const { default: path } = await import("node:path")

  const implementationTasksPath = resolvePlanArtifactPath(changeId, planVersion, "implementation-tasks", cwd)
  try {
    await fs.access(implementationTasksPath)
    return false
  } catch {
    // Missing; synthesize below if execution groups are available.
  }

  const executionGroupsPath = resolvePlanArtifactPath(changeId, planVersion, "execution-groups", cwd)
  let executionGroupsContent = ""
  try {
    executionGroupsContent = await fs.readFile(executionGroupsPath, "utf-8")
  } catch {
    return false
  }

  const groups = parseExecutionGroupsMd(executionGroupsContent)
  if (groups.length === 0) return false

  const lines: string[] = [
    "# Implementation Tasks",
    "",
    "<!-- zflow-synthesized-artifact: implementation-tasks -->",
    "",
    `Generated by zflow-change-prepare for change \`${changeId}\` ${planVersion}.`,
    "",
    "> This is a synthesized recovery artifact because the planner did not produce a real implementation-tasks.md.",
    "> It is useful for inspection and repair, but it is NOT sufficient for plan approval.",
    "",
    "This artifact contains focused implementation task specs for each execution group.",
    "Use it together with `design.md`, `execution-groups.md`, `standards.md`, and `verification.md`.",
    "",
    "## Context Index",
    "",
    "- Overall problem, architecture, and decisions: `design.md`",
    "- Execution order, ownership, dependencies, review tags, and scoped verification: `execution-groups.md`",
    "- Project conventions, commands, boundaries, and quality gates: `standards.md`",
    "- End-to-end and per-group verification expectations: `verification.md`",
    "- Per-group implementation task details: this file",
    "",
    "## Global Worker Rules",
    "",
    "### Always",
    "- Read the matching group section in this file before editing code.",
    "- Modify only the files listed for the assigned execution group unless a deviation is reported.",
    "- Run the scoped verification command from the group before reporting completion.",
    "",
    "### Ask first / stop and report drift",
    "- The likely file list is incomplete for the implementation that is actually required.",
    "- The pseudocode conflicts with existing code patterns or the approved design.",
    "- A dependency, schema, migration, or public API change is needed but not described by the plan.",
    "",
    "### Never",
    "- Start unrelated refactors while implementing a group.",
    "- Remove or weaken tests to make verification pass.",
    "- Edit runtime plan artifacts during implementation.",
    "",
  ]

  for (const group of groups) {
    const groupNumber = group.id.replace(/^group-/, "")
    const files = group.files.length > 0 ? group.files : ["No files listed in execution-groups.md; stop and report a plan-quality gap before editing."]
    const dependencies = group.dependencies.length > 0 ? group.dependencies.join(", ") : "None"
    const verification = group.scopedVerification ?? "No scoped verification command listed; stop and report a plan-quality gap before implementation."

    lines.push(
      `## Group ${groupNumber}: ${group.taskPrompt || group.id}`,
      "",
      `Group ID: \`${group.id}\`  `,
      `Assigned agent: \`${group.agent}\`  `,
      `Dependencies: ${dependencies}`,
      "",
      "### Objective",
      group.taskPrompt || `Implement the approved work for ${group.id}.`,
      "",
      "### Scope",
      "Included:",
      `- Complete only the work described for \`${group.id}\` in \`execution-groups.md\`.`,
      "- Preserve existing behavior outside the group scope.",
      "",
      "Excluded:",
      "- Unrelated cleanup, broad refactors, or opportunistic rewrites.",
      "- Files outside the listed scope unless plan drift is reported and approved.",
      "",
      "### Likely files touched",
      "",
      "| File | Operation | Reason | Notes |",
      "| --- | --- | --- | --- |",
      ...files.map((file) => `| \`${file}\` | modify | Required by ${group.id} scope | Follow existing local patterns before editing |`),
      "",
      "### Context to read first",
      "- `design.md` sections related to this group",
      "- `execution-groups.md` entry for this group and all dependencies",
      "- `standards.md` commands, code style, and boundaries",
      "- Nearby tests and existing implementations for each likely touched file",
      "",
      "### Implementation checklist",
      "1. Read the context listed above and confirm the group scope.",
      "2. Inspect each likely touched file and identify the smallest safe change.",
      "3. Apply the change using existing project patterns and naming conventions.",
      "4. Add or update focused tests when behavior changes.",
      "5. Run the scoped verification command and capture the result.",
      "6. Summarize changed files, verification output, and any deviations.",
      "",
      "### Pseudocode / implementation sketch",
      "```text",
      `read design.md, standards.md, verification.md, and execution-groups.md for ${group.id}`,
      "for each likely touched file:",
      "  inspect existing patterns and related tests",
      "  make the smallest change that satisfies the group objective",
      "  update or add focused tests when behavior changes",
      "run the scoped verification command",
      "if scope or files differ materially from the plan:",
      "  stop and report plan drift instead of expanding the task silently",
      "```",
      "",
      "### Acceptance criteria",
      `- The objective for \`${group.id}\` is implemented without unrelated changes.`,
      "- Only listed files are modified, or an approved deviation explains why more files were needed.",
      "- Relevant tests or checks are updated when behavior changes.",
      "- Scoped verification passes or the failure is reported with actionable details.",
      "",
      "### Scoped verification",
      "```bash",
      verification,
      "```",
      "",
      "### Self-check before completion",
      "- [ ] Did I read this task spec and the linked plan artifacts?",
      "- [ ] Did I touch only the listed files, or report drift?",
      "- [ ] Did I preserve existing patterns and boundaries?",
      "- [ ] Did I add/update focused tests when behavior changed?",
      "- [ ] Did I run scoped verification and record the result?",
      "",
      "### Drift triggers",
      "- A required file is absent from the likely touched file list.",
      "- The existing code architecture contradicts the implementation sketch.",
      "- Verification cannot be run as written.",
      "- The group cannot be completed independently after its dependencies finish.",
      "",
    )
  }

  const result = await writePlanArtifact({
    changeId,
    planVersion,
    artifact: "implementation-tasks",
    content: lines.join("\n"),
  }, cwd)

  if (!result.ok) {
    // Tolerate mixed local installs where the workflow package has been
    // updated before the artifact writer allowlist. Validation/review need the
    // file to exist, so fall back to a direct workflow-owned write rather than
    // leaving prepare blocked. Fully updated installs still take the metadata
    // recording path above.
    await fs.mkdir(path.dirname(implementationTasksPath), { recursive: true })
    await fs.writeFile(implementationTasksPath, lines.join("\n"), "utf-8")
  }

  return true
}
