/**
 * plan-artifact-validator.ts — Deterministic markdown contract validation
 * for plan artifacts generated by /zflow-change-prepare.
 *
 * Validates artifacts against machine-ingestible format contracts before
 * plan approval. Integrates with parseExecutionGroupsMd() for the most
 * critical artifact (execution-groups.md).
 *
 * @module pi-zflow-change-workflows/plan-artifact-validator
 */

// Re-export the parser for convenience
import { resolvePlanArtifactPath } from "pi-zflow-artifacts/artifact-paths"

// ── Types ────────────────────────────────────────────────────────

/**
 * Result of validating a single plan artifact.
 */
export interface ArtifactValidationResult {
  /** Whether this artifact passes all validation rules. */
  valid: boolean
  /** Artifact name: "design", "execution-groups", "standards", "verification", "implementation-tasks". */
  artifact: string
  /** Human-readable issue descriptions. */
  issues: string[]
  /** Absolute path to the artifact file. */
  path: string
}

/**
 * Result of validating all five canonical plan artifacts.
 */
export interface AllArtifactsValidationResult {
  /** True only when every artifact passes. */
  valid: boolean
  /** Per-artifact results. */
  results: ArtifactValidationResult[]
  /** One-line summary for status display. */
  summary: string
}

// ── Constants ────────────────────────────────────────────────────

/**
 * The five canonical plan artifact identifiers.
 */
export const CANONICAL_ARTIFACT_IDS = [
  "design",
  "execution-groups",
  "standards",
  "verification",
  "implementation-tasks",
] as const

/**
 * Minimum content lengths per artifact (to reject trivial placeholders).
 */
const MIN_CONTENT_LENGTHS: Record<string, number> = {
  design: 50,
  "execution-groups": 100,
  standards: 50,
  verification: 50,
  "implementation-tasks": 100,
}

/**
 * Placeholder patterns that should never appear in approved artifacts.
 */
const PLACEHOLDER_PATTERNS: RegExp[] = [
  /\[TODO\]/i,
  /\[placeholder\]/i,
  /awaiting\s+(scout|repo\.mapper|planner)/i,
  /TODO:\s*(write|fill|implement|add)/i,
  /TBD/i,
]

// ── Execution-groups heading pattern ─────────────────────────────

/**
 * Regex matching group headings in execution-groups.md.
 * Supports:
 *   ## Group 1: Name
 *   ## G1 — Name
 *   ## Execution Group 1: Name
 *   ### Group A1: Name
 *   # Group 1: Name (h1 also accepted)
 *   ## Group 1A: Name
 */
const GROUP_HEADING_RE = /^#{1,4}\s+Group\s+([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s*(?::|[—-])\s+.+$/im

/**
 * Regex matching "## G1 — Name" shorthand format.
 */
const GROUP_SHORT_HEADING_RE = /^#{1,4}\s+G([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s+[—-]\s+.+$/im

/**
 * Regex matching "## Execution Group 1: Name" format.
 */
const GROUP_EXEC_HEADING_RE = /^#{1,4}\s+Execution\s+Group\s+([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s*(?::|[—-])\s+.+$/im

// ── Required field patterns for execution groups ─────────────────

/**
 * Patterns to detect the files section heading.
 */
const FILES_HEADER_RE = /^\*{0,2}Files?(?:\/paths)?\*{0,2}:|^\*{0,2}Primary\s+files?(?:\/paths)?\s+touched\*{0,2}:/im

/**
 * Pattern to detect scoped verification with a concrete value (not TBD/empty).
 */
const SCOPED_VERIFICATION_RE = /\*{0,2}Scoped\s+verification:\*{0,2}[^\S\n]*(.*)$/im

/**
 * Pattern to detect agent field.
 */
const AGENT_RE = /\*{0,2}Agent\*{0,2}:\s*(.+)$/im

/**
 * Pattern to detect dependencies field.
 */
const DEPENDENCIES_RE = /\*{0,2}Dependencies\*{0,2}:\s*(.+)$/im

/**
 * Pattern to detect parallelizable field.
 */
const PARALLELIZABLE_RE = /\*{0,2}Parallelizable\*{0,2}:\s*(.+)$/im

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Check whether a string looks like a placeholder for scoped verification.
 */
function isPlaceholderOrEmpty(value: string): boolean {
  const trimmed = value.trim()
  if (!trimmed) return true
  const upper = trimmed.toUpperCase()
  if (upper === "TBD" || upper === "TODO" || upper === "NONE" || upper === "[]") return true
  if (PLACEHOLDER_PATTERNS.some((p) => p.test(trimmed))) return true
  return false
}

/**
 * Read a plan artifact file and return its content.
 */
async function readArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  cwd?: string,
): Promise<{ content: string; path: string } | null> {
  const { default: fs } = await import("node:fs/promises")
  const filePath = resolvePlanArtifactPath(changeId, planVersion, artifactId, cwd)
  try {
    const content = await fs.readFile(filePath, "utf-8")
    return { content, path: filePath }
  } catch {
    return null
  }
}

// ── Validation functions ─────────────────────────────────────────

/**
 * Validate execution-groups.md.
 *
 * Checks:
 * - At least one group heading exists
 * - Each group has Files and Scoped verification
 * - No TBD/placeholder verification commands
 * - Unique group IDs
 */
async function validateExecutionGroups(
  changeId: string,
  planVersion: string,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  const issues: string[] = []
  const artifactFile = await readArtifact(changeId, planVersion, "execution-groups", cwd)

  if (!artifactFile) {
    return {
      valid: false,
      artifact: "execution-groups",
      issues: [`execution-groups.md not found at expected path.`],
      path: resolvePlanArtifactPath(changeId, planVersion, "execution-groups", cwd),
    }
  }

  const { content, path } = artifactFile

  if (content.trim().length < 100) {
    issues.push(`Content too short (${content.trim().length} chars, minimum 100).`)
  }

  // 1. Check for at least one group heading
  const hasStandardHeading = GROUP_HEADING_RE.test(content)
  const hasShortHeading = GROUP_SHORT_HEADING_RE.test(content)
  const hasExecHeading = GROUP_EXEC_HEADING_RE.test(content)

  if (!hasStandardHeading && !hasShortHeading && !hasExecHeading) {
    issues.push(
      "No group headings found. Each group must start with a heading like:\n" +
      '  "## Group 1: Name" or "## G1 — Name" or "## Execution Group 1: Name"',
    )
    return {
      valid: false,
      artifact: "execution-groups",
      issues,
      path,
    }
  }

  // 2. Split into groups by heading and validate each
  const headingRegex = /^#{1,4}\s+(?:Group\s+|G|Execution\s+Group\s+)([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)/im
  const sections = content.split(/(?=^#{1,4}\s+(?:Group\s+|G|Execution\s+Group\s+))/m).filter(Boolean)

  if (sections.length === 0) {
    issues.push("Could not split execution-groups content into group sections.")
    return { valid: false, artifact: "execution-groups", issues, path }
  }

  const seenIds = new Set<string>()

  for (let i = 0; i < sections.length; i++) {
    const section = sections[i]!

    // Extract group ID
    const idMatch = section.match(headingRegex)
    if (!idMatch) {
      // Section heading doesn't look like a group heading — could be
      // a document title (# Execution Groups) or preamble. Skip it.
      continue
    }
    const groupId = idMatch[1].toLowerCase()

    // Check for duplicate IDs
    if (seenIds.has(groupId)) {
      issues.push(`Group "${groupId}" (section ${i + 1}): duplicate group ID. Each group must have a unique ID.`)
    }
    seenIds.add(groupId)

    // Check Files section
    if (!FILES_HEADER_RE.test(section)) {
      issues.push(`Group "${groupId}" (section ${i + 1}): missing "Files:" or "Primary files/paths touched:" section.`)
    }

    // Check Scoped verification
    const verificationMatch = section.match(SCOPED_VERIFICATION_RE)
    if (!verificationMatch) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): missing "Scoped verification:" field. ` +
        "Each group must specify a concrete verification command.",
      )
    } else {
      const verificationValue = verificationMatch[1].trim()
      if (isPlaceholderOrEmpty(verificationValue)) {
        issues.push(
          `Group "${groupId}" (section ${i + 1}): scoped verification "${verificationValue}" is a placeholder. ` +
          "Provide a concrete command, not TBD or TODO.",
        )
      }
    }
  }

  if (issues.length === 0) {
    return { valid: true, artifact: "execution-groups", issues: [], path }
  }

  return { valid: false, artifact: "execution-groups", issues, path }
}

/**
 * Validate a simple (non-execution-groups) artifact.
 *
 * Checks:
 * - File exists and has content above minimum length
 * - No placeholder markers
 */
async function validateSimpleArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  minLength: number,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  const issues: string[] = []
  const artifactFile = await readArtifact(changeId, planVersion, artifactId, cwd)

  const filePath = resolvePlanArtifactPath(changeId, planVersion, artifactId, cwd)

  if (!artifactFile) {
    return {
      valid: false,
      artifact: artifactId,
      issues: [`${artifactId}.md not found at expected path: ${filePath}`],
      path: filePath,
    }
  }

  const { content } = artifactFile

  if (content.trim().length < minLength) {
    issues.push(
      `Content too short (${content.trim().length} chars, minimum ${minLength}). ` +
      "Artifact may contain only placeholder text.",
    )
  }

  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(content)) {
      issues.push(`Contains placeholder marker (matched: ${pattern.source}). Replace with concrete content.`)
    }
  }

  // Additional checks for verification.md
  if (artifactId === "verification") {
    const hasCodeFence = /```/.test(content)
    if (!hasCodeFence) {
      issues.push("Should contain at least one code fence (```) with a verification command.")
    }
  }

  if (issues.length === 0) {
    return { valid: true, artifact: artifactId, issues: [], path: filePath }
  }

  return { valid: false, artifact: artifactId, issues, path: filePath }
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Validate all five canonical plan artifacts for a change.
 *
 * Also runs ownership validation on execution-groups.md to catch file
 * overlap issues early (during prepare) rather than at implementation time.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param cwd - Working directory (optional).
 * @returns Combined validation result with per-artifact breakdown.
 */
export async function validateAllPlanArtifacts(
  changeId: string,
  planVersion: string,
  cwd?: string,
): Promise<AllArtifactsValidationResult> {
  const results: ArtifactValidationResult[] = []

  // Validate execution-groups.md (most complex + critical)
  results.push(await validateExecutionGroups(changeId, planVersion, cwd))

  // Validate simpler artifacts
  for (const artifactId of CANONICAL_ARTIFACT_IDS) {
    if (artifactId === "execution-groups") continue // already done
    const minLen = MIN_CONTENT_LENGTHS[artifactId] ?? 50
    results.push(await validateSimpleArtifact(changeId, planVersion, artifactId, minLen, cwd))
  }

  // ── Ownership validation ───────────────────────────────────
  // Catch file-overlap/dependency issues early so the repair loop
  // can fix them before plan approval. This runs even if format
  // validation already flagged execution-groups — the planner
  // should fix all issues in one repair pass.
  const execGroupsResult = results.find((r) => r.artifact === "execution-groups")
  if (execGroupsResult && execGroupsResult.valid) {
    try {
      const artifactFile = await readArtifact(changeId, planVersion, "execution-groups", cwd)
      if (artifactFile) {
        const { parseExecutionGroupsMd } = await import("./orchestration.js")
        const { validateOwnershipAndDependencies } = await import("./ownership-validator.js")
        const groups = parseExecutionGroupsMd(artifactFile.content)
        const ownershipResult = validateOwnershipAndDependencies(groups)
        if (!ownershipResult.valid) {
          results.push({
            valid: false,
            artifact: "execution-groups",
            issues: [ownershipResult.summary],
            path: execGroupsResult.path,
          })
        }
      }
    } catch {
      // Ownership validation is best-effort during prepare;
      // the implement-time check is the hard gate.
    }
  }

  const valid = results.every((r) => r.valid)
  const validCount = results.filter((r) => r.valid).length
  const totalCount = results.length
  const summary = valid
    ? `All ${totalCount} plan artifacts are valid.`
    : `${validCount}/${totalCount} plan artifacts valid. ${totalCount - validCount} artifact(s) have issues.`

  return { valid, results, summary }
}

/**
 * Validate a single plan artifact by ID.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param artifactId - Artifact name ("design", "execution-groups", etc.).
 * @param cwd - Working directory (optional).
 * @returns Validation result for that artifact.
 */
export async function validateSingleArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  if (artifactId === "execution-groups") {
    return validateExecutionGroups(changeId, planVersion, cwd)
  }

  const minLen = MIN_CONTENT_LENGTHS[artifactId] ?? 50
  return validateSimpleArtifact(changeId, planVersion, artifactId, minLen, cwd)
}

/**
 * Re-export the placeholder pattern check for reuse.
 */
export { isPlaceholderOrEmpty }

/**
 * Result of an artifact repair attempt.
 */
export interface ArtifactRepairResult {
  /** Whether ALL failed artifacts were repaired successfully. */
  repaired: boolean
  /** Issues that remain after max attempts. */
  remainingIssues: ArtifactValidationResult[]
  /** Number of repair attempts made. */
  attempts: number
}

/**
 * Build a focused repair prompt for the planner agent, listing exactly which
 * artifacts failed validation and why.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param failedResults - The validation results for artifacts that failed.
 * @param cwd - Working directory (optional).
 * @returns A prompt string for the planner agent.
 */
export async function buildRepairPrompt(
  changeId: string,
  planVersion: string,
  failedResults: ArtifactValidationResult[],
  cwd?: string,
): Promise<string> {
  const { default: pathModule } = await import("node:path")
  const { resolvePlanVersionDir } = await import("pi-zflow-artifacts/artifact-paths")

  const versionDir = resolvePlanVersionDir(changeId, planVersion, cwd)

  const sections: string[] = [
    `# Artifact Repair — ${changeId} ${planVersion}`,
    "",
    "Your plan artifacts failed automated validation. Below are the EXACT",
    "parser errors that must be fixed. Rewrite ONLY the artifacts listed.",
    "",
    "## Instructions",
    "",
    "1. Read each validation error below carefully.",
    "2. Rewrite ONLY the artifact(s) listed — do not touch artifacts that passed.",
    "3. Use zflow_write_plan_artifact for all artifact writes.",
    "4. After writing, the artifacts will be re-validated automatically.",
    "5. Do NOT add new TODOs, placeholders, or TBD values.",
    "6. Do NOT rewrite the execution-groups heading structure — use the same heading format.",
    "",
    "## Artifact paths",
    "",
  ]

  for (const result of failedResults) {
    const artifactPath = pathModule.join(versionDir, `${result.artifact}.md`)
    sections.push(`### ${result.artifact}.md`)
    sections.push(`**Path:** ${artifactPath}`)
    sections.push("")
    if (result.issues.length > 0) {
      sections.push("**Validation errors:**")
      for (const issue of result.issues) {
        sections.push(`- ${issue}`)
      }
    }
    sections.push("")
  }

  // Detect ownership-specific failures and add targeted guidance
  const hasOwnershipIssues = failedResults.some(
    (r) => r.artifact === "execution-groups" && r.issues.some((i) => i.includes("ambiguous file overlaps") || i.includes("ownership")),
  )

  sections.push(
    "## Format contract reminder",
    "",
    "### execution-groups.md",
    "",
    "Required per group:",
    "- Heading: `## Group X: Name` where X is a unique ID (1, 1A, A1, etc.)",
    "- `**Files:**` — concrete file paths",
    "- `**Scoped verification:**` — a real shell command (NOT TBD)",
    "- `**Agent:**` — agent name (e.g. zflow.implement-routine)",
    "- `**Dependencies:**` — group IDs or 'none'",
    "- `**Parallelizable:**` — true or false",
    "",
  )

  if (hasOwnershipIssues) {
    sections.push(
      "### Fixing ownership conflicts",
      "",
      "The groups above share files but lack dependency ordering. To fix:",
      "",
      "1. For each pair of conflicting groups (GX, GY) that share a file:",
      "   - One must declare a dependency on the other (e.g. GY adds `7` to its Dependencies).",
      "   - Choose the dependency direction based on logical execution order.",
      "2. Set `Parallelizable: false` on groups that now have cross-group dependencies.",
      "3. Re-read the full execution-groups.md after editing to verify:",
      "   - No two groups claim the same file without a dependency edge between them.",
      "   - Dependency chains are cycle-free.",
      "4. Use zflow_write_plan_artifact with artifact=execution-groups to write the fix.",
      "",
    )
  }

  sections.push(
    "### Other artifacts",
    "",
    "- Must contain real content, not placeholders or TODOs.",
    "- verification.md needs at least one code fence with a command.",
    "- Minimum content lengths: design=50ch, standards=50ch, verification=50ch, implementation-tasks=100ch.",
    "",
    `## Change: ${changeId}`,
    `## Version: ${planVersion}`,
  )

  return sections.join("\n")
}

/**
 * Attempt to repair failed plan artifacts by dispatching the planner frontend
 * with focused validation errors.
 *
 * Uses the registry to find a dispatch service (zflow-dispatch). If none is
 * available, returns immediately without repair.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param failedResults - The validation results for artifacts that failed.
 * @param maxAttempts - Maximum repair attempts (default: 2).
 * @param cwd - Working directory (optional).
 * @returns Repair result with remaining issues.
 */
export async function runArtifactRepair(
  changeId: string,
  planVersion: string,
  failedResults: ArtifactValidationResult[],
  maxAttempts: number = 2,
  cwd?: string,
): Promise<ArtifactRepairResult> {
  const { default: fs } = await import("node:fs/promises")
  const { default: pathModule } = await import("node:path")
  const { resolvePlanVersionDir, resolvePlanArtifactPath } = await import("pi-zflow-artifacts/artifact-paths")
  const { getZflowRegistry } = await import("pi-zflow-core/registry")
  const { DISPATCH_SERVICE_CAPABILITY } = await import("pi-zflow-core/dispatch-service")

  const registry = getZflowRegistry()
  const zflowDispatch = registry.optional<{ runAgent?: Function }>(DISPATCH_SERVICE_CAPABILITY)

  if (!zflowDispatch || typeof zflowDispatch.runAgent !== "function") {
    console.info("[zflow] No dispatch service available for artifact repair. Skipping repair pass.")
    return { repaired: false, remainingIssues: failedResults, attempts: 0 }
  }

  const remaining = [...failedResults]
  let attempts = 0

  for (attempts = 1; attempts <= maxAttempts; attempts++) {
    if (remaining.length === 0) break

    const repairPrompt = await buildRepairPrompt(changeId, planVersion, remaining, cwd)
    const versionDir = resolvePlanVersionDir(changeId, planVersion, cwd)
    const repairOutputPath = pathModule.join(versionDir, `repair-attempt-${attempts}.md`)

    console.info(`[zflow] Artifact repair attempt ${attempts}/${maxAttempts} (${remaining.length} artifact(s) remaining).`)

    try {
      const result = await zflowDispatch.runAgent({
        agent: "zflow.planner-frontier",
        task: repairPrompt,
        cwd: cwd ?? process.cwd(),
        output: repairOutputPath,
        outputMode: "file-only",
        maxOutput: { lines: 300, bytes: 20000 },
      })

      if (!result.ok) {
        console.warn(`[zflow] Artifact repair attempt ${attempts} failed: ${result.error ?? "unknown error"}`)
        continue
      }
    } catch (err) {
      console.warn(`[zflow] Artifact repair attempt ${attempts} threw: ${err instanceof Error ? err.message : String(err)}`)
      continue
    }

    // Re-validate the remaining artifacts
    const newResults: ArtifactValidationResult[] = []
    for (const failed of remaining) {
      const recheck = await validateSingleArtifact(changeId, planVersion, failed.artifact, cwd)
      newResults.push(recheck)
    }

    // Keep only artifacts that still fail
    const stillFailed = newResults.filter((r) => !r.valid)
    remaining.length = 0
    remaining.push(...stillFailed)
  }

  const repaired = remaining.length === 0
  return { repaired, remainingIssues: remaining, attempts }
}
