/**
 * plan-artifact-validator.ts — Deterministic markdown contract validation
 * for plan artifacts generated by /zflow-change-prepare.
 *
 * Validates artifacts against machine-ingestible format contracts before
 * plan approval. Integrates with parseExecutionGroupsMd() for the most
 * critical artifact (execution-groups.md).
 *
 * @module pi-zflow-change-workflows/plan-artifact-validator
 */

// Re-export the parser for convenience
import { resolvePlanArtifactPath } from "pi-zflow-artifacts/artifact-paths"

// ── Types ────────────────────────────────────────────────────────

/**
 * Result of validating a single plan artifact.
 */
export interface ArtifactValidationResult {
  /** Whether this artifact passes all validation rules. */
  valid: boolean
  /** Artifact name: "design", "execution-groups", "standards", "verification", "implementation-tasks". */
  artifact: string
  /** Human-readable issue descriptions. */
  issues: string[]
  /** Absolute path to the artifact file. */
  path: string
}

/**
 * Result of validating all five canonical plan artifacts.
 */
export interface AllArtifactsValidationResult {
  /** True only when every artifact passes. */
  valid: boolean
  /** Per-artifact results. */
  results: ArtifactValidationResult[]
  /** One-line summary for status display. */
  summary: string
}

// ── Constants ────────────────────────────────────────────────────

/**
 * The five canonical plan artifact identifiers.
 */
export const CANONICAL_ARTIFACT_IDS = [
  "design",
  "execution-groups",
  "standards",
  "verification",
  "implementation-tasks",
] as const

/**
 * Minimum content lengths per artifact (to reject trivial placeholders).
 */
const MIN_CONTENT_LENGTHS: Record<string, number> = {
  design: 50,
  "execution-groups": 100,
  standards: 50,
  verification: 50,
  "implementation-tasks": 100,
}

/**
 * Placeholder patterns that should never appear in approved artifacts.
 */
const PLACEHOLDER_PATTERNS: RegExp[] = [
  /\[TODO\]/i,
  /\[placeholder\]/i,
  /awaiting\s+(scout|repo\.mapper|planner)/i,
  /TODO:\s*(write|fill|implement|add)/i,
  /TBD/i,
]

// ── Execution-groups heading pattern ─────────────────────────────

/**
 * Regex matching group headings in execution-groups.md.
 * Supports:
 *   ## Group 1: Name
 *   ## G1 — Name
 *   ## Execution Group 1: Name
 *   ### Group A1: Name
 *   # Group 1: Name (h1 also accepted)
 *   ## Group 1A: Name
 */
const GROUP_HEADING_RE = /^#{1,4}\s+Group\s+([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s*(?::|[—-])\s+.+$/im

/**
 * Regex matching "## G1 — Name" shorthand format.
 */
const GROUP_SHORT_HEADING_RE = /^#{1,4}\s+G([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s+[—-]\s+.+$/im

/**
 * Regex matching "## Execution Group 1: Name" format.
 */
const GROUP_EXEC_HEADING_RE = /^#{1,4}\s+Execution\s+Group\s+([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)\s*(?::|[—-])\s+.+$/im

// ── Required field patterns for execution groups ─────────────────
//
// Note: All field regexes below match normalized field labels with
// bold markers already stripped. The normalizeFieldBold() helper is
// applied to each group section BEFORE field matching, so the regexes
// do not need to handle asterisk/bold variants.

/**
 * Pattern to normalize bold markers around field labels.
 *
 * LLMs sometimes write fields with the colon inside the bold markers:
 *   **Execution mode:** isolated   ← colon inside bold (common LLM output)
 * Instead of the canonical:
 *   **Execution mode:** isolated   ← colon after bold (expected by regex)
 *
 * This normalizer strips leading ** and trailing ** before/after
 * the colon on field-label lines, so all field regexes can use simple
 * "FieldName:" patterns without worrying about bold variants.
 */
function normalizeFieldBold(section: string): string {
  // Match optional bullet prefixes plus bolded field labels such as:
  //   - **Execution mode:** isolated
  //   **Files touched (≤7):**
  // and rewrite them to plain `FieldName: ` form while preserving the bullet.
  // Uses [^\S\n] (non-newline whitespace) instead of \s to avoid
  // consuming newlines and collapsing adjacent field lines together.
  return section.replace(
    /^(\s*(?:[-*+]|\d+\.)\s+)?\*{1,2}([^*\n:][^:\n]*?)\*{0,2}:[^\S\n]*(\*{0,2})[^\S\n]*/gm,
    (_, prefix = "", fieldName) => `${prefix}${fieldName.trim()}: `,
  )
}

/**
 * Patterns to detect the files section heading.
 */
const FILES_HEADER_RE = /^(?:\s*(?:[-*+]|\d+\.)\s+)?(?:Files?(?:\s+touched)?(?:\/paths)?(?:\s*\([^)]*\))?|Primary\s+files?(?:\/paths)?\s+touched):/im

/**
 * Pattern to detect scoped verification with a concrete value (not TBD/empty).
 * Uses [^\S\n] (non-newline whitespace) instead of \s to avoid consuming
 * newlines when the field value is empty or missing.
 */
const SCOPED_VERIFICATION_RE = /Scoped\s+verification:[^\S\n]*(.*)$/im

/**
 * Pattern to detect agent field.
 */
const AGENT_RE = /(?:Owner\s+agent|Agent|Owner):[^\S\n]*(.+)$/im

/**
 * Pattern to detect dependencies field.
 */
const DEPENDENCIES_RE = /Dependencies:[^\S\n]*(.+)$/im

/**
 * Pattern to detect parallelizable field.
 */
const PARALLELIZABLE_RE = /Parallelizable:[^\S\n]*(.+)$/im

/** Pattern to detect execution mode field. */
const EXECUTION_MODE_RE = /Execution\s+mode:[^\S\n]*(.+)$/im

/** Pattern to detect workspace id field. */
const WORKSPACE_ID_RE = /Workspace\s+ID:[^\S\n]*(.+)$/im

/** Pattern to detect workspace concurrency field. */
const WORKSPACE_CONCURRENCY_RE = /Workspace\s+concurrency:[^\S\n]*(.+)$/im

/** Pattern to detect base strategy field. */
const BASE_STRATEGY_RE = /Base\s+strategy:[^\S\n]*(.+)$/im

/** Pattern to detect execution rationale field. */
const EXECUTION_RATIONALE_RE = /Execution\s+rationale:[^\S\n]*(.+)$/im

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Check whether a string looks like a placeholder for scoped verification.
 */
function isPlaceholderOrEmpty(value: string): boolean {
  const trimmed = value.trim()
  if (!trimmed) return true
  const upper = trimmed.toUpperCase()
  if (upper === "TBD" || upper === "TODO" || upper === "NONE" || upper === "[]") return true
  if (PLACEHOLDER_PATTERNS.some((p) => p.test(trimmed))) return true
  return false
}

/**
 * Check which failed plan artifacts exist on disk.
 *
 * Returns the subset of failedResults that exist on disk, plus a list
 * of artifact names that are missing entirely. Useful for deciding
 * whether a repair dispatch should regenerate missing artifacts or
 * only fix formatting issues in existing ones.
 */
async function checkArtifactExistence(
  changeId: string,
  planVersion: string,
  failedResults: ArtifactValidationResult[],
  cwd?: string,
): Promise<{
  existing: ArtifactValidationResult[]
  missingArtifacts: string[]
}> {
  const { default: fs } = await import("node:fs/promises")
  const { resolvePlanArtifactPath } = await import("pi-zflow-artifacts/artifact-paths")

  const existing: ArtifactValidationResult[] = []
  const missingArtifacts: string[] = []

  for (const failed of failedResults) {
    try {
      await fs.access(resolvePlanArtifactPath(changeId, planVersion, failed.artifact, cwd))
      existing.push(failed)
    } catch {
      missingArtifacts.push(failed.artifact)
    }
  }

  return { existing, missingArtifacts }
}

/**
 * Read a plan artifact file and return its content.
 */
async function readArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  cwd?: string,
): Promise<{ content: string; path: string } | null> {
  const { default: fs } = await import("node:fs/promises")
  const filePath = resolvePlanArtifactPath(changeId, planVersion, artifactId, cwd)
  try {
    const content = await fs.readFile(filePath, "utf-8")
    return { content, path: filePath }
  } catch {
    return null
  }
}

// ── Validation functions ─────────────────────────────────────────

/**
 * Validate execution-groups.md.
 *
 * Checks:
 * - At least one group heading exists
 * - Each group has Files and Scoped verification
 * - No TBD/placeholder verification commands
 * - Unique group IDs
 */
async function validateExecutionGroups(
  changeId: string,
  planVersion: string,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  const issues: string[] = []
  const artifactFile = await readArtifact(changeId, planVersion, "execution-groups", cwd)

  if (!artifactFile) {
    return {
      valid: false,
      artifact: "execution-groups",
      issues: [`execution-groups.md not found at expected path.`],
      path: resolvePlanArtifactPath(changeId, planVersion, "execution-groups", cwd),
    }
  }

  const { content, path } = artifactFile

  if (content.trim().length < 100) {
    issues.push(`Content too short (${content.trim().length} chars, minimum 100).`)
  }

  const { parseExecutionGroupsMd } = await import("./orchestration.js")
  const parsedGroupsById = new Map(
    parseExecutionGroupsMd(content).map((group) => [group.id.replace(/^group-/, "").toLowerCase(), group]),
  )

  // 1. Check for at least one group heading
  const hasStandardHeading = GROUP_HEADING_RE.test(content)
  const hasShortHeading = GROUP_SHORT_HEADING_RE.test(content)
  const hasExecHeading = GROUP_EXEC_HEADING_RE.test(content)

  if (!hasStandardHeading && !hasShortHeading && !hasExecHeading) {
    issues.push(
      "No group headings found. Each group must start with a heading like:\n" +
      '  "## Group 1: Name" or "## G1 — Name" or "## Execution Group 1: Name"',
    )
    return {
      valid: false,
      artifact: "execution-groups",
      issues,
      path,
    }
  }

  // 2. Split into groups by heading and validate each
  const headingRegex = /^#{1,4}\s+(?:Group\s+|G|Execution\s+Group\s+)([A-Za-z]?\d+[A-Za-z]?|\d+[A-Za-z]?)/im
  const sections = content.split(/(?=^#{1,4}\s+(?:Group\s+|G|Execution\s+Group\s+))/m).filter(Boolean)

  if (sections.length === 0) {
    issues.push("Could not split execution-groups content into group sections.")
    return { valid: false, artifact: "execution-groups", issues, path }
  }

  const seenIds = new Set<string>()

  for (let i = 0; i < sections.length; i++) {
    const section = sections[i]!

    // Extract group ID
    const idMatch = section.match(headingRegex)
    if (!idMatch) {
      // Section heading doesn't look like a group heading — could be
      // a document title (# Execution Groups) or preamble. Skip it.
      continue
    }
    const groupId = idMatch[1].toLowerCase()

    // Check for duplicate IDs
    if (seenIds.has(groupId)) {
      issues.push(`Group "${groupId}" (section ${i + 1}): duplicate group ID. Each group must have a unique ID.`)
    }
    seenIds.add(groupId)

    // Normalize bold markers in field labels before matching
    // LLMs may write "**FieldName:** value" (colon inside bold) instead
    // of the expected "**FieldName:** value" (colon after bold). The
    // normalizer strips leading/trailing ** around the field label so
    // that all field regexes below can use simple "FieldName:" patterns.
    const normalizedSection = normalizeFieldBold(section)

    // Check Files section
    if (!FILES_HEADER_RE.test(normalizedSection)) {
      issues.push(`Group "${groupId}" (section ${i + 1}): missing "Files:" or "Primary files/paths touched:" section.`)
    }

    // Check Scoped verification. Use the parser-derived value when present so
    // multi-line bullet lists and fenced command blocks stay aligned with the
    // runtime parser rather than being rejected by a narrower regex.
    const verificationMatch = normalizedSection.match(SCOPED_VERIFICATION_RE)
    const parsedGroup = parsedGroupsById.get(groupId)
    const verificationValue = parsedGroup?.scopedVerification?.trim() ?? verificationMatch?.[1]?.trim() ?? ""
    if (!verificationMatch && !verificationValue) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): missing "Scoped verification:" field. ` +
        "Each group must specify a concrete verification command.",
      )
    } else if (isPlaceholderOrEmpty(verificationValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): scoped verification "${verificationValue}" is a placeholder. ` +
        "Provide a concrete command, not TBD or TODO.",
      )
    }

    // Check Agent field
    const agentMatch = normalizedSection.match(AGENT_RE)
    if (!agentMatch || !agentMatch[1].trim()) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): missing "Agent:" field. ` +
        "Each group must specify an agent (e.g. zflow.implement-routine).",
      )
    }

    // Check Dependencies field
    const depMatch = normalizedSection.match(DEPENDENCIES_RE)
    if (!depMatch || !depMatch[1].trim()) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): missing "Dependencies:" field. ` +
        "Each group must specify dependencies or \"none\".",
      )
    }

    // Check optional Parallelizable field. Legacy/planner output may omit it;
    // the runtime parser defaults omitted values to true, so validation should
    // stay aligned with the parser instead of rejecting otherwise-valid groups.
    const parallelMatch = normalizedSection.match(PARALLELIZABLE_RE)
    const parallelValue = parallelMatch?.[1]?.trim().toLowerCase()
    if (parallelValue && !["true", "false", "yes", "no"].includes(parallelValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): invalid "Parallelizable:" value "${parallelMatch![1].trim()}". ` +
        "Use true or false.",
      )
    }

    // Check optional advanced execution strategy fields
    const executionModeValue = parsedGroup?.executionMode ?? normalizedSection.match(EXECUTION_MODE_RE)?.[1]?.trim().toLowerCase() ?? "isolated"
    const workspaceIdValue = parsedGroup?.workspaceId ?? normalizedSection.match(WORKSPACE_ID_RE)?.[1]?.trim().replace(/^`|`$/g, "")
    const workspaceConcurrencyValue = parsedGroup?.workspaceConcurrency ?? normalizedSection.match(WORKSPACE_CONCURRENCY_RE)?.[1]?.trim().toLowerCase() ?? "serialized"
    const baseStrategyValue = parsedGroup?.baseStrategy ?? normalizedSection.match(BASE_STRATEGY_RE)?.[1]?.trim().toLowerCase() ?? "head"
    const executionRationaleValue = parsedGroup?.executionRationale ?? normalizedSection.match(EXECUTION_RATIONALE_RE)?.[1]?.trim() ?? ""

    if (!["isolated", "shared-staging"].includes(executionModeValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): invalid execution mode "${executionModeValue}". ` +
        "Use isolated or shared-staging.",
      )
    }

    if (!["serialized", "concurrent"].includes(workspaceConcurrencyValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): invalid workspace concurrency "${workspaceConcurrencyValue}". ` +
        "Use serialized or concurrent.",
      )
    }

    if (!["head", "dependency-lineage"].includes(baseStrategyValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): invalid base strategy "${baseStrategyValue}". ` +
        "Use head or dependency-lineage.",
      )
    }

    if (executionModeValue === "shared-staging" && !workspaceIdValue) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): shared-staging groups must declare "Workspace ID:".`,
      )
    }

    if (workspaceConcurrencyValue === "concurrent" && executionModeValue !== "shared-staging") {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): workspace concurrency "concurrent" requires "Execution mode: shared-staging".`,
      )
    }

    if (baseStrategyValue === "dependency-lineage") {
      const depsValue = depMatch?.[1]?.trim().toLowerCase() ?? ""
      if (!depsValue || depsValue === "none") {
        issues.push(
          `Group "${groupId}" (section ${i + 1}): base strategy "dependency-lineage" requires at least one dependency.`,
        )
      }
    }

    const usesNonDefaultExecution =
      executionModeValue !== "isolated" ||
      workspaceConcurrencyValue !== "serialized" ||
      baseStrategyValue !== "head"

    if (usesNonDefaultExecution && isPlaceholderOrEmpty(executionRationaleValue)) {
      issues.push(
        `Group "${groupId}" (section ${i + 1}): non-default execution strategy requires a concrete "Execution rationale:" field.`,
      )
    }
  }

  if (issues.length === 0) {
    return { valid: true, artifact: "execution-groups", issues: [], path }
  }

  return { valid: false, artifact: "execution-groups", issues, path }
}

/**
 * Validate a simple (non-execution-groups) artifact.
 *
 * Checks:
 * - File exists and has content above minimum length
 * - No placeholder markers
 */
async function validateSimpleArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  minLength: number,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  const issues: string[] = []
  const artifactFile = await readArtifact(changeId, planVersion, artifactId, cwd)

  const filePath = resolvePlanArtifactPath(changeId, planVersion, artifactId, cwd)

  if (!artifactFile) {
    return {
      valid: false,
      artifact: artifactId,
      issues: [`${artifactId}.md not found at expected path: ${filePath}`],
      path: filePath,
    }
  }

  const { content } = artifactFile

  if (content.trim().length < minLength) {
    issues.push(
      `Content too short (${content.trim().length} chars, minimum ${minLength}). ` +
      "Artifact may contain only placeholder text.",
    )
  }

  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(content)) {
      issues.push(`Contains placeholder marker (matched: ${pattern.source}). Replace with concrete content.`)
    }
  }

  // Additional checks for verification.md
  if (artifactId === "verification") {
    const hasCodeFence = /```/.test(content)
    if (!hasCodeFence) {
      issues.push("Should contain at least one code fence (```) with a verification command.")
    }
  }

  if (issues.length === 0) {
    return { valid: true, artifact: artifactId, issues: [], path: filePath }
  }

  return { valid: false, artifact: artifactId, issues, path: filePath }
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Validate all five canonical plan artifacts for a change.
 *
 * Also runs ownership validation on execution-groups.md to catch file
 * overlap issues early (during prepare) rather than at implementation time.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param cwd - Working directory (optional).
 * @returns Combined validation result with per-artifact breakdown.
 */
export async function validateAllPlanArtifacts(
  changeId: string,
  planVersion: string,
  cwd?: string,
): Promise<AllArtifactsValidationResult> {
  const results: ArtifactValidationResult[] = []

  // Validate execution-groups.md (most complex + critical)
  results.push(await validateExecutionGroups(changeId, planVersion, cwd))

  // Validate simpler artifacts
  for (const artifactId of CANONICAL_ARTIFACT_IDS) {
    if (artifactId === "execution-groups") continue // already done
    const minLen = MIN_CONTENT_LENGTHS[artifactId] ?? 50
    results.push(await validateSimpleArtifact(changeId, planVersion, artifactId, minLen, cwd))
  }

  // ── Ownership validation ───────────────────────────────────
  // Catch file-overlap/dependency issues early so the repair loop
  // can fix them before plan approval. This runs even if format
  // validation already flagged execution-groups — the planner
  // should fix all issues in one repair pass.
  const execGroupsResult = results.find((r) => r.artifact === "execution-groups")
  if (execGroupsResult && execGroupsResult.valid) {
    try {
      const artifactFile = await readArtifact(changeId, planVersion, "execution-groups", cwd)
      if (artifactFile) {
        const { parseExecutionGroupsMd } = await import("./orchestration.js")
        const { validateOwnershipAndDependencies } = await import("./ownership-validator.js")
        const groups = parseExecutionGroupsMd(artifactFile.content)
        const ownershipResult = validateOwnershipAndDependencies(groups)
        if (!ownershipResult.valid) {
          results.push({
            valid: false,
            artifact: "execution-groups",
            issues: [ownershipResult.summary],
            path: execGroupsResult.path,
          })
        }
      }
    } catch {
      // Ownership validation is best-effort during prepare;
      // the implement-time check is the hard gate.
    }
  }

  const valid = results.every((r) => r.valid)
  const validCount = results.filter((r) => r.valid).length
  const totalCount = results.length
  const summary = valid
    ? `All ${totalCount} plan artifacts are valid.`
    : `${validCount}/${totalCount} plan artifacts valid. ${totalCount - validCount} artifact(s) have issues.`

  return { valid, results, summary }
}

/**
 * Validate a single plan artifact by ID.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param artifactId - Artifact name ("design", "execution-groups", etc.).
 * @param cwd - Working directory (optional).
 * @returns Validation result for that artifact.
 */
export async function validateSingleArtifact(
  changeId: string,
  planVersion: string,
  artifactId: string,
  cwd?: string,
): Promise<ArtifactValidationResult> {
  if (artifactId === "execution-groups") {
    return validateExecutionGroups(changeId, planVersion, cwd)
  }

  const minLen = MIN_CONTENT_LENGTHS[artifactId] ?? 50
  return validateSimpleArtifact(changeId, planVersion, artifactId, minLen, cwd)
}

/**
 * Re-export the placeholder pattern check for reuse.
 */
export { isPlaceholderOrEmpty }

/**
 * Result of an artifact repair attempt.
 */
export interface ArtifactRepairResult {
  /** Whether ALL failed artifacts were repaired successfully. */
  repaired: boolean
  /** Issues that remain after max attempts. */
  remainingIssues: ArtifactValidationResult[]
  /** Number of repair attempts made. */
  attempts: number
}

/**
 * Build a focused repair prompt for the planner agent, listing exactly which
 * artifacts failed validation and why.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param failedResults - The validation results for artifacts that failed.
 * @param cwd - Working directory (optional).
 * @param missingArtifacts - Optional list of artifact names that don't exist on disk
 *   and need full creation (not just repair).
 * @returns A prompt string for the planner agent.
 */
export async function buildRepairPrompt(
  changeId: string,
  planVersion: string,
  failedResults: ArtifactValidationResult[],
  cwd?: string,
  missingArtifacts?: string[],
): Promise<string> {
  const { default: pathModule } = await import("node:path")
  const { resolvePlanVersionDir } = await import("pi-zflow-artifacts/artifact-paths")

  const versionDir = resolvePlanVersionDir(changeId, planVersion, cwd)

  const sections: string[] = [
    `# Artifact Repair — ${changeId} ${planVersion}`,
    "",
    "Your plan artifacts failed automated validation. Below are the EXACT",
    "parser errors that must be fixed. Rewrite ONLY the artifacts listed.",
    "",
    "## Instructions",
    "",
    "1. Read each validation error below carefully.",
    "2. Rewrite ONLY the artifact(s) listed — do not touch artifacts that passed.",
    "3. Use zflow_write_plan_artifact for all artifact writes.",
    "4. After writing, the artifacts will be re-validated automatically.",
    "5. Do NOT add new TODOs, placeholders, or TBD values.",
    "6. Do NOT rewrite the execution-groups heading structure — use the same heading format.",
    "",
    "## Artifact paths",
    "",
  ]

  for (const result of failedResults) {
    const artifactPath = pathModule.join(versionDir, `${result.artifact}.md`)
    sections.push(`### ${result.artifact}.md`)
    sections.push(`**Path:** ${artifactPath}`)
    sections.push("")
    if (result.issues.length > 0) {
      sections.push("**Validation errors:**")
      for (const issue of result.issues) {
        sections.push(`- ${issue}`)
      }
    }
    sections.push("")
  }

  // Add missing artifacts section if any don't exist on disk
  if (missingArtifacts && missingArtifacts.length > 0) {
    sections.push("### Missing Artifacts (need full creation)")
    sections.push("")
    sections.push("The following artifacts do not exist on disk yet and need to be created from scratch:")
    for (const name of missingArtifacts) {
      const artifactPath = pathModule.join(versionDir, `${name}.md`)
      sections.push(`- **${name}**: ${artifactPath}`)
    }
    sections.push("")
    sections.push("Use zflow_write_plan_artifact to write these files with complete content.")
    sections.push("")
  }

  // Detect ownership-specific failures and add targeted guidance
  const hasOwnershipIssues = failedResults.some(
    (r) => r.artifact === "execution-groups" && r.issues.some((i) => i.includes("ambiguous file overlaps") || i.includes("ownership")),
  )

  sections.push(
    "## Format contract reminder",
    "",
    "### execution-groups.md",
    "",
    "Required per group:",
    "- Heading: `## Group X: Name` where X is a unique ID (1, 1A, A1, etc.)",
    "- `**Files:**` — concrete file paths",
    "- `**Scoped verification:**` — a real shell command (NOT TBD)",
    "- `**Agent:**` — agent name (e.g. zflow.implement-routine)",
    "- `**Dependencies:**` — group IDs or 'none'",
    "- `**Parallelizable:**` — true or false",
    "",
  )

  if (hasOwnershipIssues) {
    sections.push(
      "### Fixing ownership conflicts",
      "",
      "The groups above share files but lack dependency ordering. To fix:",
      "",
      "1. For each pair of conflicting groups (GX, GY) that share a file:",
      "   - One must declare a dependency on the other (e.g. GY adds `7` to its Dependencies).",
      "   - Choose the dependency direction based on logical execution order.",
      "2. Set `Parallelizable: false` on groups that now have cross-group dependencies.",
      "3. Re-read the full execution-groups.md after editing to verify:",
      "   - No two groups claim the same file without a dependency edge between them.",
      "   - Dependency chains are cycle-free.",
      "4. Use zflow_write_plan_artifact with artifact=execution-groups to write the fix.",
      "",
    )
  }

  sections.push(
    "### Other artifacts",
    "",
    "- Must contain real content, not placeholders or TODOs.",
    "- verification.md needs at least one code fence with a command.",
    "- Minimum content lengths: design=50ch, standards=50ch, verification=50ch, implementation-tasks=100ch.",
    "",
    `## Change: ${changeId}`,
    `## Version: ${planVersion}`,
  )

  return sections.join("\n")
}

/**
 * Attempt to repair failed plan artifacts by dispatching the planner frontend
 * with focused validation errors.
 *
 * Uses the registry to find a dispatch service (zflow-dispatch). If none is
 * available, returns immediately without repair.
 *
 * @param changeId - The change identifier.
 * @param planVersion - Plan version (e.g. "v1").
 * @param failedResults - The validation results for artifacts that failed.
 * @param maxAttempts - Maximum repair attempts (default: 2).
 * @param cwd - Working directory (optional).
 * @returns Repair result with remaining issues.
 */
export async function runArtifactRepair(
  changeId: string,
  planVersion: string,
  failedResults: ArtifactValidationResult[],
  maxAttempts: number = 2,
  cwd?: string,
): Promise<ArtifactRepairResult> {
  const { default: fs } = await import("node:fs/promises")
  const { default: pathModule } = await import("node:path")
  const { resolvePlanVersionDir, resolvePlanArtifactPath } = await import("pi-zflow-artifacts/artifact-paths")
  const { getZflowRegistry } = await import("pi-zflow-core/registry")
  const { DISPATCH_SERVICE_CAPABILITY } = await import("pi-zflow-core/dispatch-service")

  const registry = getZflowRegistry()
  const zflowDispatch = registry.optional<{ runAgent?: Function }>(DISPATCH_SERVICE_CAPABILITY)

  if (!zflowDispatch || typeof zflowDispatch.runAgent !== "function") {
    console.info("[zflow] No dispatch service available for artifact repair. Skipping repair pass.")
    return { repaired: false, remainingIssues: failedResults, attempts: 0 }
  }

  // Check which failed artifacts actually exist on disk. If an artifact
  // file is missing entirely (e.g. the initial planner dispatch completely
  // failed before writing it), the repair prompt needs to note that.
  const { missingArtifacts } = await checkArtifactExistence(changeId, planVersion, failedResults, cwd)

  const remaining = [...failedResults]
  let attempts = 0

  for (attempts = 1; attempts <= maxAttempts; attempts++) {
    if (remaining.length === 0) break

    const repairPrompt = await buildRepairPrompt(changeId, planVersion, remaining, cwd, missingArtifacts)
    const versionDir = resolvePlanVersionDir(changeId, planVersion, cwd)
    const repairOutputPath = pathModule.join(versionDir, `repair-attempt-${attempts}.md`)

    console.info(`[zflow] Artifact repair attempt ${attempts}/${maxAttempts} (${remaining.length} artifact(s) remaining).`)

    try {
      const result = await zflowDispatch.runAgent({
        agent: "zflow.planner-frontier",
        task: repairPrompt,
        cwd: cwd ?? process.cwd(),
        output: repairOutputPath,
        outputMode: "file-only",
        maxOutput: { lines: 300, bytes: 20000 },
      })

      if (!result.ok) {
        console.warn(`[zflow] Artifact repair attempt ${attempts} failed: ${result.error ?? "unknown error"}`)
        continue
      }
    } catch (err) {
      console.warn(`[zflow] Artifact repair attempt ${attempts} threw: ${err instanceof Error ? err.message : String(err)}`)
      continue
    }

    // Re-validate the remaining artifacts
    const newResults: ArtifactValidationResult[] = []
    for (const failed of remaining) {
      const recheck = await validateSingleArtifact(changeId, planVersion, failed.artifact, cwd)
      newResults.push(recheck)
    }

    // Keep only artifacts that still fail
    const stillFailed = newResults.filter((r) => !r.valid)
    remaining.length = 0
    remaining.push(...stillFailed)
  }

  const repaired = remaining.length === 0
  return { repaired, remainingIssues: remaining, attempts }
}
