/**
 * prepare-full-workflow.test.ts — Unit tests for Phase 7.5/7.9 prepare and implement workflow functions.
 */
import * as assert from "node:assert"
import { test, describe } from "node:test"
import * as fs from "node:fs/promises"
import * as path from "node:path"
import * as os from "node:os"
import { execFileSync } from "node:child_process"

import {
  runChangePrepareWorkflow,
  advancePlanLifecycle,
  runPlanValidation,
  runPlanReview,
  approvePlanVersion,
  buildHandoffContext,
  runChangeImplementWorkflow,
  finalizeVerification,
  completeWorkflow,
} from "../extensions/zflow-change-workflows/orchestration.js"

import { resolvePlanStatePath, resolvePlanVersionDir, resolveRunStatePath, resolveStateIndexPath, resolveReconnaissancePath, resolveRepoMapPath } from "pi-zflow-artifacts/artifact-paths"

import { loadStateIndex } from "pi-zflow-artifacts/state-index"

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/**
 * Create a temporary directory initialized as a git repo so that runtime
 * state path resolution works correctly (git-dir based).
 */
async function createTestRepo(): Promise<string> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "zflow-test-full-"))
  execFileSync("git", ["init"], { cwd: tmpDir, encoding: "utf-8", stdio: "pipe" })
  execFileSync("git", ["config", "user.email", "test@test.com"], { cwd: tmpDir, encoding: "utf-8", stdio: "pipe" })
  execFileSync("git", ["config", "user.name", "Test User"], { cwd: tmpDir, encoding: "utf-8", stdio: "pipe" })
  // Create an initial commit so git rev-parse HEAD works
  await fs.writeFile(path.join(tmpDir, "README.md"), "# Test", "utf-8")
  execFileSync("git", ["add", "."], { cwd: tmpDir, encoding: "utf-8", stdio: "pipe" })
  execFileSync("git", ["commit", "-m", "Initial commit"], { cwd: tmpDir, encoding: "utf-8", stdio: "pipe" })
  return tmpDir
}

/**
 * Clean up a temporary test repo.
 */
async function removeTestRepo(repoRoot: string): Promise<void> {
  await fs.rm(repoRoot, { recursive: true, force: true })
}

/**
 * Write placeholder plan artifacts so validation passes.
 */
async function writeValidPlanArtifacts(versionDir: string): Promise<void> {
  await fs.mkdir(versionDir, { recursive: true })
  await fs.writeFile(path.join(versionDir, "design.md"), "# Design\n\nReal design content", "utf-8")
  await fs.writeFile(path.join(versionDir, "execution-groups.md"), "# Execution Groups\n\nReal execution groups", "utf-8")
  await fs.writeFile(path.join(versionDir, "standards.md"), "# Standards\n\nReal standards content", "utf-8")
  await fs.writeFile(path.join(versionDir, "verification.md"), "# Verification\n\nReal verification plan", "utf-8")
}

// ---------------------------------------------------------------------------
// Tests — runChangePrepareWorkflow enhancements
// ---------------------------------------------------------------------------

describe("runChangePrepareWorkflow — enhanced steps", () => {
  test("creates v1 dir with all canonical artifact placeholder paths", async () => {
    const repoRoot = await createTestRepo()
    try {
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-placeholders",
      })

      // Verify the v1 directory exists and artifact paths are set
      const versionDir = path.dirname(result.artifactPaths.design)
      const dirStat = await fs.stat(versionDir)
      assert.ok(dirStat.isDirectory(), "v1 directory should exist")

      // Artifact paths should all be under the version dir
      assert.ok(result.artifactPaths.design.endsWith("design.md"))
      assert.ok(result.artifactPaths.executionGroups.endsWith("execution-groups.md"))
      assert.ok(result.artifactPaths.standards.endsWith("standards.md"))
      assert.ok(result.artifactPaths.verification.endsWith("verification.md"))
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("writes concrete reconnaissance.md and repo-map.md", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-concrete-files",
      })

      // Check reconnaissance.md has concrete content
      const reconPath = resolveReconnaissancePath(repoRoot)
      const reconContent = await fs.readFile(reconPath, "utf-8")
      assert.ok(reconContent.includes("Reconnaissance"), "reconnaissance.md should have heading")
      assert.ok(reconContent.includes("Generated by"), "reconnaissance.md should have generation timestamp")
      assert.ok(reconContent.includes("Change path"), "reconnaissance.md should have scope section")
      assert.ok(reconContent.includes("README"), "reconnaissance.md should reference README")
      // No placeholder markers
      assert.ok(!reconContent.includes("Awaiting scout"), "reconnaissance.md should not contain scout placeholder")
      assert.ok(!reconContent.includes("(to be filled by scout)"), "reconnaissance.md should not contain scout filler")

      // Check repo-map.md has concrete repo data
      const repoMapPathResolved = resolveRepoMapPath(repoRoot)
      const repoMapContent = await fs.readFile(repoMapPathResolved, "utf-8")
      assert.ok(repoMapContent.includes("Repository Map"), "repo-map.md should have heading")
      assert.ok(repoMapContent.includes("Generated by"), "repo-map.md should have generation timestamp")
      // Should contain actual git info from the test repo
      assert.ok(repoMapContent.includes("Branch"), "repo-map.md should include branch info")
      assert.ok(repoMapContent.includes("HEAD"), "repo-map.md should include HEAD sha")
      assert.ok(repoMapContent.includes("README.md"), "repo-map.md should list top-level files")
      // No placeholder markers
      assert.ok(!repoMapContent.includes("Awaiting repo-mapper"), "repo-map.md should not contain repo-mapper placeholder")
      assert.ok(!repoMapContent.includes("(to be filled by repo-mapper)"), "repo-map.md should not contain repo-mapper filler")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — advancePlanLifecycle
// ---------------------------------------------------------------------------

describe("advancePlanLifecycle", () => {
  test("transitions lifecycle state correctly", async () => {
    const repoRoot = await createTestRepo()
    try {
      // Create initial plan state
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-lifecycle",
      })

      // Advance through states
      await advancePlanLifecycle("test-lifecycle", "validated", repoRoot)
      let planState = JSON.parse(await fs.readFile(result.planStatePath, "utf-8"))
      assert.strictEqual(planState.lifecycleState, "validated")

      await advancePlanLifecycle("test-lifecycle", "reviewed", repoRoot)
      planState = JSON.parse(await fs.readFile(result.planStatePath, "utf-8"))
      assert.strictEqual(planState.lifecycleState, "reviewed")

      await advancePlanLifecycle("test-lifecycle", "approved", repoRoot)
      planState = JSON.parse(await fs.readFile(result.planStatePath, "utf-8"))
      assert.strictEqual(planState.lifecycleState, "approved")

      // Also verify state-index entry was updated
      const index = await loadStateIndex(repoRoot)
      const planEntry = index.entries.find(
        (e) => e.type === "plan" && e.metadata?.changeId === "test-lifecycle",
      )
      assert.ok(planEntry, "plan entry should exist in state index")
      assert.strictEqual(planEntry!.status, "approved")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — runPlanValidation
// ---------------------------------------------------------------------------

describe("runPlanValidation", () => {
  test("detects missing artifacts", async () => {
    const repoRoot = await createTestRepo()
    try {
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-missing-artifacts",
      })

      // Don't write artifacts — they should be missing
      const validation = await runPlanValidation("test-missing-artifacts", "v1", repoRoot)
      assert.strictEqual(validation.pass, false)
      assert.ok(validation.issues.length >= 4, "should have at least 4 issues (one per missing artifact)")
      assert.ok(validation.issues.some((i) => i.includes("design.md")), "should mention missing design.md")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("passes when artifacts exist and have real content", async () => {
    const repoRoot = await createTestRepo()
    try {
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-valid-artifacts",
      })

      // Write valid plan artifacts
      const versionDir = path.dirname(result.artifactPaths.design)
      await writeValidPlanArtifacts(versionDir)

      const validation = await runPlanValidation("test-valid-artifacts", "v1", repoRoot)
      assert.strictEqual(validation.pass, true)
      assert.strictEqual(validation.issues.length, 0)
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("detects placeholder markers in artifacts", async () => {
    const repoRoot = await createTestRepo()
    try {
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-placeholder-markers",
      })

      // Write artifacts with placeholder markers
      const versionDir = path.dirname(result.artifactPaths.design)
      await fs.mkdir(versionDir, { recursive: true })
      await fs.writeFile(path.join(versionDir, "design.md"), "# Design\n[TODO] fill this in", "utf-8")
      await fs.writeFile(path.join(versionDir, "execution-groups.md"), "# Execution Groups\nawaiting scout dispatch", "utf-8")
      await fs.writeFile(path.join(versionDir, "standards.md"), "# Standards\nTODO: write standards", "utf-8")
      await fs.writeFile(path.join(versionDir, "verification.md"), "# Verification\nReal verification plan", "utf-8")

      const validation = await runPlanValidation("test-placeholder-markers", "v1", repoRoot)
      assert.strictEqual(validation.pass, false)
      assert.ok(validation.issues.length >= 3, "should detect at least 3 placeholder issues")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — approvePlanVersion
// ---------------------------------------------------------------------------

describe("approvePlanVersion", () => {
  test("sets approvedVersion and marks version immutable", async () => {
    const repoRoot = await createTestRepo()
    try {
      const result = await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-approve",
      })

      // Approve version v1
      await approvePlanVersion("test-approve", "v1", repoRoot)

      // Verify plan state
      const planState = JSON.parse(await fs.readFile(result.planStatePath, "utf-8"))
      assert.strictEqual(planState.approvedVersion, "v1")
      assert.strictEqual(planState.lifecycleState, "approved")
      assert.strictEqual(planState.versions.v1.state, "approved")
      assert.ok(planState.versions.v1.immutableAt, "immutableAt should be set")

      // Verify state-index was updated
      const index = await loadStateIndex(repoRoot)
      const planEntry = index.entries.find(
        (e) => e.type === "plan" && e.metadata?.changeId === "test-approve",
      )
      assert.ok(planEntry, "plan entry should exist")
      assert.strictEqual(planEntry!.status, "approved")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — buildHandoffContext
// ---------------------------------------------------------------------------

describe("buildHandoffContext", () => {
  test("returns handoff metadata with plan artifact paths", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-handoff",
      })

      const handoff = await buildHandoffContext("test-handoff", "v1", repoRoot)
      assert.strictEqual(handoff.changeId, "test-handoff")
      assert.strictEqual(handoff.approvedVersion, "v1")
      assert.ok(handoff.runtimeStateDir, "runtimeStateDir should be set")
      assert.ok(handoff.planArtifactPaths, "planArtifactPaths should be set")
      assert.ok(handoff.planArtifactPaths.design, "design path should be set")
      assert.ok(handoff.planArtifactPaths.executionGroups, "executionGroups path should be set")
      assert.ok(handoff.planArtifactPaths.standards, "standards path should be set")
      assert.ok(handoff.planArtifactPaths.verification, "verification path should be set")
      assert.ok(handoff.forkedAt, "forkedAt timestamp should be set")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — runChangeImplementWorkflow
// ---------------------------------------------------------------------------

describe("runChangeImplementWorkflow", () => {
  test("creates proper run.json and returns status executing", async () => {
    const repoRoot = await createTestRepo()
    try {
      // First create and approve a plan
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-impl",
      })
      await approvePlanVersion("test-impl", "v1", repoRoot)

      // Now run implementation
      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-impl",
      })

      assert.strictEqual(result.changeId, "test-impl")
      assert.strictEqual(result.status, "executing", "status should be 'executing', not 'completed'")
      assert.ok(result.runId, "runId should be set")
      assert.ok(result.runId.startsWith("impl-"), "runId should start with 'impl-'")
      assert.strictEqual(result.planVersion, "v1")

      // Verify run.json exists
      const runStatePath = resolveRunStatePath(result.runId, repoRoot)
      const runContent = await fs.readFile(runStatePath, "utf-8")
      const runJson = JSON.parse(runContent)
      assert.strictEqual(runJson.runId, result.runId)
      assert.strictEqual(runJson.changeId, "test-impl")
      assert.strictEqual(runJson.planVersion, "v1")
      assert.strictEqual(runJson.phase, "executing")
      assert.ok(runJson.createdAt, "createdAt should be set")
      assert.ok(runJson.repoRoot, "repoRoot should be set")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("rejects missing approved plan", async () => {
    const repoRoot = await createTestRepo()
    try {
      // Create plan but don't approve it
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-no-approve",
      })

      await assert.rejects(
        async () => {
          await runChangeImplementWorkflow({
            cwd: repoRoot,
            changeId: "test-no-approve",
          })
        },
        {
          message: /No approved plan/,
        },
      )
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("rejects when no plan exists", async () => {
    const repoRoot = await createTestRepo()
    try {
      await assert.rejects(
        async () => {
          await runChangeImplementWorkflow({
            cwd: repoRoot,
            changeId: "no-plan-exists",
          })
        },
        {
          message: /No plan found/,
        },
      )
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("detects dirty worktree", async () => {
    const repoRoot = await createTestRepo()
    try {
      // Create and approve plan
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-dirty",
      })
      await approvePlanVersion("test-dirty", "v1", repoRoot)

      // Create uncommitted change
      await fs.writeFile(path.join(repoRoot, "untracked.txt"), "dirty", "utf-8")

      // Without --force, dirty tree must throw
      await assert.rejects(
        () => runChangeImplementWorkflow({
          cwd: repoRoot,
          changeId: "test-dirty",
        }),
        { message: /Primary worktree must be clean/ },
      )

      // With --force, dirty tree is allowed
      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-dirty",
        force: true,
      })
      assert.strictEqual(result.status, "executing")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("detects plan state advancing to executing", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-state-change",
      })
      await approvePlanVersion("test-state-change", "v1", repoRoot)

      await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-state-change",
      })

      const planStatePath = resolvePlanStatePath("test-state-change", repoRoot)
      const planState = JSON.parse(await fs.readFile(planStatePath, "utf-8"))
      assert.strictEqual(planState.lifecycleState, "executing")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("writes nextSteps array into run.json", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-next-steps",
      })
      await approvePlanVersion("test-next-steps", "v1", repoRoot)

      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-next-steps",
      })

      // Verify result includes nextSteps
      assert.ok(Array.isArray(result.nextSteps), "result.nextSteps should be an array")
      assert.ok(result.nextSteps.length > 0, "result.nextSteps should have entries")

      // Verify run.json contains nextSteps
      const runStatePath = resolveRunStatePath(result.runId, repoRoot)
      const runJson = JSON.parse(await fs.readFile(runStatePath, "utf-8"))
      assert.ok(Array.isArray(runJson.nextSteps), "run.json nextSteps should be an array")
      assert.strictEqual(runJson.nextSteps.length, result.nextSteps.length)
      assert.ok(runJson.nextSteps[0].includes("Context-builder"), "first step should mention context-builder")
      assert.ok(runJson.nextSteps[1].includes("Worktree dispatch"), "second step should mention worktree dispatch")
      assert.ok(runJson.nextSteps[2].includes("Worker verification"), "third step should mention worker verification")
      assert.ok(runJson.nextSteps[3].includes("Apply-back"), "fourth step should mention apply-back")
      assert.ok(runJson.nextSteps[4].includes("Final verification"), "fifth step should mention final verification")
      assert.ok(runJson.nextSteps[5].includes("Code review"), "sixth step should mention code review")
      assert.ok(runJson.nextSteps[6].includes("Fix loop"), "seventh step should mention fix loop")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("registers unfinished run in state-index change lifecycle", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-unfinished-lifecycle",
      })
      await approvePlanVersion("test-unfinished-lifecycle", "v1", repoRoot)

      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-unfinished-lifecycle",
      })

      // Verify change lifecycle has the run in unfinishedRuns
      const index = await loadStateIndex(repoRoot)
      const lifecycle = index.changes["test-unfinished-lifecycle"]
      assert.ok(lifecycle, "change lifecycle should exist")
      assert.strictEqual(lifecycle.lastPhase, "executing")
      assert.ok(Array.isArray(lifecycle.unfinishedRuns), "unfinishedRuns should be an array")
      assert.ok(lifecycle.unfinishedRuns.includes(result.runId), "runId should be in unfinishedRuns")

      // Verify state-index entry exists with status executing
      const runEntry = index.entries.find((e) => e.type === "run" && e.id === result.runId)
      assert.ok(runEntry, "run state-index entry should exist")
      assert.strictEqual(runEntry!.status, "executing")
      assert.strictEqual(runEntry!.metadata?.changeId, "test-unfinished-lifecycle")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })

  test("run.json phase is executing with metadata field", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-phase-executing",
      })
      await approvePlanVersion("test-phase-executing", "v1", repoRoot)

      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-phase-executing",
      })

      // Verify run.json phase
      const runStatePath = resolveRunStatePath(result.runId, repoRoot)
      const runJson = JSON.parse(await fs.readFile(runStatePath, "utf-8"))
      assert.strictEqual(runJson.phase, "executing")
      assert.ok(runJson.metadata, "run.json should have metadata field")
      assert.strictEqual(runJson.metadata.worktreeDirty, false)
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests — completeWorkflow
// ---------------------------------------------------------------------------

describe("completeWorkflow", () => {
  test("marks plan lifecycle as completed", async () => {
    const repoRoot = await createTestRepo()
    try {
      await runChangePrepareWorkflow({
        cwd: repoRoot,
        changeId: "test-complete",
      })
      await approvePlanVersion("test-complete", "v1", repoRoot)

      const result = await runChangeImplementWorkflow({
        cwd: repoRoot,
        changeId: "test-complete",
      })

      await completeWorkflow("test-complete", result.runId, repoRoot)

      // Verify plan state
      const planStatePath = resolvePlanStatePath("test-complete", repoRoot)
      const planState = JSON.parse(await fs.readFile(planStatePath, "utf-8"))
      assert.strictEqual(planState.lifecycleState, "completed")

      // Verify run.json phase
      const runStatePath = resolveRunStatePath(result.runId, repoRoot)
      const runJson = JSON.parse(await fs.readFile(runStatePath, "utf-8"))
      assert.strictEqual(runJson.phase, "completed")

      // Verify state-index
      const index = await loadStateIndex(repoRoot)
      const planEntry = index.entries.find(
        (e) => e.type === "plan" && e.metadata?.changeId === "test-complete",
      )
      assert.ok(planEntry, "plan entry should exist")
      assert.strictEqual(planEntry!.status, "completed")
    } finally {
      await removeTestRepo(repoRoot)
    }
  })
})
